environment:
  matrix:
  - example: simple-player
    name: win32
    platform: amd64_x86
    qt: msvc2013
  - example: simple-player
    name: win64
    platform: amd64
    qt: msvc2013_64
  - example: simple-player
    name: win32
    platform: mingw
    qt: mingw492_32

  - example: qml-player
    name: win32
    platform: amd64_x86
    qt: msvc2013
  - example: qml-player
    name: win64
    platform: amd64
    qt: msvc2013_64
  - example: qml-player
    name: win32
    platform: mingw
    qt: mingw492_32

install:
  - set PATH=C:\Qt\5.5\%qt%\bin;C:\dev\dependencies\vlc-qt\bin;%PATH%
  - set ORIGPATH=%PATH%
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set makefiles="NMake Makefiles") else (set makefiles="MinGW Makefiles")

build_script:
  - if %platform%==mingw set PATH=C:\Qt\5.5\%qt%\bin;C:\dev\dependencies\vlc-qt\bin;C:\Qt\Tools\mingw492_32\bin;C:\Program Files (x86)\CMake\bin
  - cd build
  - cmake . -G %makefiles% -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="c:/dev/install"
  - if not %platform%==mingw (nmake) else (mingw32-make)
  - if not %platform%==mingw (nmake install) else (mingw32-make install)
  - if not %platform%==mingw (nmake windows) else (mingw32-make windows)
  - if %platform%==mingw set PATH=%ORIGPATH%