environment:
  matrix:
    - GENERATOR : "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTDIR: C:\Qt\6.7.0\msvc2019_64
      PLATFORM: x64
    - GENERATOR : "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTDIR: C:\Qt\6.7.0\msvc2019_32
      PLATFORM: Win32

configuration:
  - Release

install:
  - set PATH=%QTDIR%\bin;%PATH%
  - set Qt6_DIR=%QTDIR%\lib\cmake\Qt6
  - set PATH=C:\Program Files\Git\usr\bin;%PATH%

before_build:
  - mkdir build
  - cd build
  - mkdir bin
  - set OUTPUT_DIR=%cd%\bin
  - cmake "-G%GENERATOR%"
    -DCMAKE_PREFIX_PATH=%Qt6_DIR%
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG="%OUTPUT_DIR%"
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE="%OUTPUT_DIR%"
    ..


build_script:
  - cmake --build .