language: cpp
sudo: true
compiler: gcc
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - make
      - qttools5-dev
      - qt5-qmake

before_script:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.2-xenial
  - sudo apt-get -y update
  - sudo apt-get install -y gcc-6 g++-6 
  - sudo apt-get install -y qt511base
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10
  - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 20
  - sudo update-alternatives --set cc /usr/bin/gcc
  - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 20
  - sudo update-alternatives --set c++ /usr/bin/g++
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - echo $LANG
  - echo $LC_ALL
  - export CXX="g++-6" CC="gcc-6"
  - sudo apt-get update -qq

script: 
  - gcc -v
  - g++ -v
  - mkdir build
  - cd build
  - qmake ../LogView.pro
  - make
