language: cpp
sudo: true
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - clang
      - cmake
      - qt5-default
      - qt5-qmake
      - make

before_script:
  - echo $LANG
  - echo $LC_ALL
  - export CXX="g++-6" CC="gcc-6"
  - sudo apt-get update -qq

script: 
  - mkdir build
  - cd build
  - qmake -d -d -d ../LogView.pro
  - make