anguage: cpp
sudo: true
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - clang
      - cmake
      - qt5-default
      - qt5-qmake
      - make

before_install:
  - echo $LANG
  - echo $LC_ALL

script: 
  - mkdir build
  - cd build
  - qmake ../LogView.pro
  - make