language: minimal
dist: xenial

services:
  - docker

install:
  - ci/create_docker_image.sh    

script: 
  - docker run --security-opt seccomp:unconfined -v ${PWD}:/root/logview logview:1 /root/logview/ci/build_app.sh 
