FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y -qq --no-install-recommends \
        cmake \
        g++ \
        make \
        qt6-base-dev \
        qt6-tools-dev


ENTRYPOINT ["/bin/bash"]
